# Generated by Django 4.2.16 on 2026-04-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_product_img_url_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
