# Generated by Django 4.2.16 on 2026-04-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_adminuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="adminuser",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
